public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        byte box = 8;
        System.out.println("Значение переменной с типом byte равно " + box);
        short apple = 130;
        System.out.println("Значение переменной с типом short равно " + apple);
        int banan = 1000;
        System.out.println("Значение переменной с типом int равно " + banan);
        long day = 350L;
        System.out.println("Значение переменной с типом long равно " + day);
        float pepper = 3.17f;
        System.out.println("Значение переменной с типом float равно " + pepper);
        double cucumber = 25.125;
        System.out.println("Значение переменной с типом double равно " + cucumber);
        System.out.println("Задача 2");
        float a = 27.12f;
        System.out.println(a);
        long b = 987678965549L;
        System.out.println(b);
        float c = 2.786f;
        System.out.println(c);
        short d = 569;
        System.out.println(d);
        short i = -159;
        System.out.println(i);
        int f = 27897;
        System.out.println(f);
        byte j = 67;
        System.out.println(j);
        System.out.println("Задача 3");
        byte class1 = 23;
        byte class2 = 27;
        byte class3 = 30;
        int totalStudents = class1 + class2 + class3;
        short totalList = 480;
        int peopleList = totalList / totalStudents;
        System.out.println("На каждого ученика рассчитано " + peopleList + " листов бумаги");
        System.out.println("Задача 4");
        byte bottle = 16;
        byte times = 2;
        int bottleOneMinute = bottle / times;
        int bottleTwentyMinute = bottleOneMinute * 20;
        System.out.println("За 20 минут машина произвела " + bottleTwentyMinute + " штук бутылок");
        int bottlesPerDay = bottleOneMinute * 1440;
        System.out.println("За 1 сутки машина произвела " + bottlesPerDay + " штук бутылок");
        int bottlesThreeDay = bottlesPerDay * 3;
        System.out.println("За 3 дня машина произвела " + bottlesThreeDay + " штук бутылок");
        int bottlesMonth = bottlesPerDay * 30;
        System.out.println("За 1 месяц машина произвела " + bottlesMonth + " штук бутылок");
        System.out.println("Задача 5");
        byte totalCans = 120;
        byte whiteCan1 = 2;
        byte brownCan1 = 4;
        int canClass1 = whiteCan1 + brownCan1;
        int totalClass = totalCans / canClass1;
        int totalWhiteCan = whiteCan1 * totalClass;
        int totalBrownCan = brownCan1 * totalClass;
        System.out.println("В школе, где " + totalClass + " классов, нужно " + totalWhiteCan + " банок белой краски и " + totalBrownCan + " банок коричневой краски");
        System.out.println("Задача 6");
        byte bananaWeight1 = 80;
        byte milk100 = 105;
        byte iceCream1 = 100;
        byte egg1 = 70;
        int bananaWeight5 = bananaWeight1 * 5;
        int milk200 = milk100 * 2;
        int iceCream2 = iceCream1 * 2;
        int egg4 = egg1 * 4;
        int breakfastWeight = bananaWeight5 + milk200 + iceCream2 + egg4;
        float breakfastWeightKg = (float) breakfastWeight / 1000;
        System.out.println("Вес спортзавтрака в граммах " + breakfastWeight);
        System.out.println("Вес спортзавтрака в КГ " + breakfastWeightKg);
        System.out.println("Задание 7");
        byte targetWeight = 7;
        int target1 = 250;
        int target2 = 500;
        float target1Kg = target1 / 1000f;
        float target2Kg = target2 / 1000f;
        float day250Grams = (float) targetWeight / target1Kg;
        float day500Grams = (float) targetWeight / target2Kg;
        System.out.println("Если худеть по 250 грамм в день, то потребуется " + day250Grams + " дней");
        System.out.println("Если худеть по 500 грамм в день, то потребуется " + day500Grams + " дней");
        float result = (day250Grams + day500Grams) / 2;
        System.out.println("в среднем потребуется " + result + " день");
        System.out.println("Задание 8");
        int startingSalary1 = 67760;
        int startingSalary2 = 83690;
        int startingSalary3 = 76230;
        int annualIncomeBeforeIncrease1 = startingSalary1 * 12;
        int annualIncomeBeforeIncrease2 = startingSalary2 * 12;
        int annualIncomeBeforeIncrease3 = startingSalary3 * 12;
        float increasedSalary1 = startingSalary1 * 1.1f;
        float increasedSalary2 = startingSalary2 * 1.1f;
        float increasedSalary3 = startingSalary3 * 1.1f;
        float annualIncome1 = increasedSalary1 * 12;
        float annualIncome2 = increasedSalary2 * 12;
        float annualIncome3 = increasedSalary3 * 12;
        float difference1 = annualIncome1 - annualIncomeBeforeIncrease1;
        float difference2 = annualIncome2 - annualIncomeBeforeIncrease2;
        float difference3 = annualIncome3 - annualIncomeBeforeIncrease3;
        System.out.println("Маша теперь получает " + increasedSalary1 + " рубля. Годовой доход вырос на " + difference1 + " рублей");
        System.out.println("Денис теперь получает " + increasedSalary2 + " рубля. Годовой доход вырос на " + difference2 + " рублей");
        System.out.println("Кристина теперь получает " + increasedSalary3 + " рубля. Годовой доход вырос на " + difference3 + " рублей");
    }

}